### ISSUE TITLE
Catalog-of-my-things-ruby-Captsone

### ISSUE THREAD

**Issue by cvalencia1991** [cvalencia1991/Ruby-Catalog-of-my-things#16]
*This is the Ruby Capstone Project we are going to work with 3 members and we are assigned by:* 
`#Team member 1` : @KanzaTahreem 
`#Team member 2` :@cvalencia1991 
`#Team member 3` : @shakerAbuDrais

**Comment by julie-ify** [comment]
Hi @KanzaTahreem, @cvalencia1991 and @shakerAbuDrais,

## Highlights!
- Descriptive pull request ✔️ 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

# Status: Approved ✔️ 

Cheers and Happy coding!👏👏👏

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
